import { Activity, Clock3, Cpu, Gauge, HardDrive, MemoryStick, Network, Pause, Play, RefreshCw, ServerCog, TriangleAlert } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { api } from "../../lib/api";
import { useAppStore } from "../../store/app-store";
import { IconButton } from "../../components/IconButton";
import { errorMessage, formatBytes } from "../../lib/format";
import { Modal } from "../../components/Modal";
import { appendMonitorHistory, type MonitorHistorySample } from "../../lib/runtime-metrics";
import { MonitorHistoryChart } from "./MonitorHistoryChart";

export function MonitorSidebar(){
  const{activeSessionId,sessions,monitor,setMonitor,settings,setError}=useAppStore();const[paused,setPaused]=useState(false);const[processesOpen,setProcessesOpen]=useState(false);const[processSort,setProcessSort]=useState<"cpu"|"memory">("cpu");const histories=useRef(new Map<string,MonitorHistorySample[]>());const active=sessions.find((item)=>item.id===activeSessionId);const currentMonitor=monitor?.sessionId===active?.id?monitor:null;const history=active?histories.current.get(active.id)??[]:[];
  useEffect(()=>{if(!active||active.sessionType==="rdp"||paused||!api.isDesktop()){if(!active||active.sessionType==="rdp")setMonitor(null);return;}let cancelled=false;let timer:number|undefined;const sessionId=active.id;const poll=async()=>{try{const snapshot=await api.monitorSnapshot(sessionId);if(!cancelled){const network=snapshot.networks.find((item)=>item.interfaceName!=="lo")??snapshot.networks[0];histories.current.set(sessionId,appendMonitorHistory(histories.current.get(sessionId)??[],{timestamp:snapshot.timestamp,cpu:snapshot.cpuPercent,received:network?.rxBytesPerSecond??0,sent:network?.txBytesPerSecond??0,latency:snapshot.latencyMs},settings.monitorIntervalMs));setMonitor(snapshot);}}catch(reason){if(!cancelled)setError(errorMessage(reason));}if(!cancelled)timer=window.setTimeout(poll,settings.monitorIntervalMs);};void poll();return()=>{cancelled=true;if(timer)clearTimeout(timer);};},[active,paused,settings.monitorIntervalMs,setError,setMonitor]);
  if(!active||active.sessionType==="rdp")return <aside className="monitor-sidebar monitor-empty"><ServerCog size={28}/><strong>服务器监控</strong><span>{active?.sessionType==="rdp"?"RDP 会话不采集 Linux 状态":"连接后显示实时状态"}</span></aside>;
  if(!currentMonitor)return <aside className="monitor-sidebar"><header><div><span className="live-indicator"/>服务器状态</div><IconButton icon={paused?Play:Pause} label={paused?"继续监控":"暂停监控"} onClick={()=>setPaused(!paused)}/></header><div className="monitor-loading"><RefreshCw className={!paused?"spin":""}/><span>{api.isDesktop()?(paused?"监控已暂停":"正在采集 Linux 状态…"):"桌面版连接后显示实时数据"}</span></div></aside>;
  const network=currentMonitor.networks.find((item)=>item.interfaceName!=="lo")??currentMonitor.networks[0];
  return <aside className="monitor-sidebar"><header><div><span className="live-indicator"/>{currentMonitor.hostname||active.title}</div><IconButton icon={paused?Play:Pause} label={paused?"继续监控":"暂停监控"} onClick={()=>setPaused(!paused)}/></header>
    <section className="host-summary"><span>{currentMonitor.ip||"远程主机"}</span><small><Clock3 size={12}/>{formatUptime(currentMonitor.uptimeSeconds)}</small><div className="load-values"><span>负载</span><b>{currentMonitor.load[0].toFixed(2)}</b><b>{currentMonitor.load[1].toFixed(2)}</b><b>{currentMonitor.load[2].toFixed(2)}</b></div></section>
    <Metric icon={Cpu} label="CPU" value={currentMonitor.cpuPercent} caption={`${currentMonitor.cpuPercent.toFixed(1)}%`}/><Sparkline values={history.map((sample)=>sample.cpu)}/>
    <Metric icon={MemoryStick} label="内存" value={percent(currentMonitor.memoryUsedBytes,currentMonitor.memoryTotalBytes)} caption={`${formatBytes(currentMonitor.memoryUsedBytes)} / ${formatBytes(currentMonitor.memoryTotalBytes)}`}/>
    <Metric icon={Gauge} label="交换" value={percent(currentMonitor.swapUsedBytes,currentMonitor.swapTotalBytes)} caption={`${formatBytes(currentMonitor.swapUsedBytes)} / ${formatBytes(currentMonitor.swapTotalBytes)}`}/>
    <section className="monitor-section process-section"><button onClick={()=>setProcessesOpen(true)}><Activity size={14}/>进程排行<span>查看全部</span></button><div className="process-list">{currentMonitor.processes.slice(0,5).map((process)=><div key={process.pid}><span title={process.command}>{process.command}</span><code>{process.memoryPercent.toFixed(1)}%</code><code>{process.cpuPercent.toFixed(1)}%</code></div>)}</div></section>
    <section className="monitor-section"><h3><Network size={14}/>网络 {network?.interfaceName}</h3><div className="network-values"><span>↓ {formatBytes(network?.rxBytesPerSecond??0)}/s</span><span>↑ {formatBytes(network?.txBytesPerSecond??0)}/s</span></div><MonitorHistoryChart samples={history} metric="network"/><small>延迟 {currentMonitor.latencyMs?.toFixed(0)??"—"} ms</small><MonitorHistoryChart samples={history} metric="latency"/></section>
    <section className="monitor-section disk-section"><h3><HardDrive size={14}/>磁盘</h3>{currentMonitor.disks.slice(0,5).map((disk)=><div key={`${disk.filesystem}-${disk.mountPoint}`}><span title={disk.mountPoint}>{disk.mountPoint}</span><div className="mini-progress"><i style={{width:`${disk.usedPercent}%`}}/></div><code>{disk.usedPercent.toFixed(0)}%</code></div>)}</section>
    {currentMonitor.warnings.map((warning)=><div className="monitor-warning" key={warning}><TriangleAlert size={13}/>{warning}</div>)}
    <footer>{paused?"已暂停 · ":""}更新于 {new Date(currentMonitor.timestamp).toLocaleTimeString()}</footer>{processesOpen&&<Modal title={`${currentMonitor.hostname} · 进程`} onClose={()=>setProcessesOpen(false)} wide><div className="process-table"><header><span>PID</span><span>用户</span><span>命令</span><button onClick={()=>setProcessSort("memory")}>内存 %</button><button onClick={()=>setProcessSort("cpu")}>CPU %</button></header>{[...currentMonitor.processes].sort((a,b)=>processSort==="cpu"?b.cpuPercent-a.cpuPercent:b.memoryPercent-a.memoryPercent).map((process)=><div key={process.pid}><code>{process.pid}</code><span>{process.user}</span><span title={process.command}>{process.command}</span><code>{process.memoryPercent.toFixed(1)}</code><code>{process.cpuPercent.toFixed(1)}</code></div>)}</div></Modal>}
  </aside>;
}

function Metric({icon:Icon,label,value,caption}:{icon:typeof Cpu;label:string;value:number;caption:string}){const normalized=Math.min(100,Math.max(0,value));return <div className="metric"><div><span><Icon size={13}/>{label}</span><strong>{caption}</strong></div><div className="metric-bar" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(normalized)} aria-valuetext={caption}><i style={{width:`${normalized}%`}}/></div></div>}
function Sparkline({values}:{values:number[]}){const points=values.length>1?values.map((value,index)=>`${index/(values.length-1)*100},${28-value/100*24}`).join(" "):"0,28 100,28";const latest=values.at(-1)??0;return <svg className="sparkline" viewBox="0 0 100 30" preserveAspectRatio="none" role="img" aria-label={`CPU 最近趋势，当前 ${latest.toFixed(1)}%`}><polyline points={points}/></svg>}
const percent=(used:number,total:number)=>total?used/total*100:0;
const formatUptime=(seconds:number)=>{const days=Math.floor(seconds/86400);const hours=Math.floor(seconds%86400/3600);return`${days} 天 ${hours} 小时`;};
