import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { api } from "../../lib/api";
import type { BackgroundTask } from "../../types";
import { NetworkDiagnostics } from "./NetworkDiagnostics";

const task:BackgroundTask={id:"task-1",kind:"networkDiagnostic",status:"completed",result:{kind:"ping",target:"example.com",output:"rtt min/avg/max/mdev = 10.0/20.0/30.0/1.0 ms",durationMs:50},error:null,createdAt:""};
describe("NetworkDiagnostics",()=>{beforeEach(()=>{vi.restoreAllMocks();vi.spyOn(api,"networkSockets").mockResolvedValue({items:[{protocol:"tcp",state:"LISTEN",localAddress:"0.0.0.0:22",peerAddress:"0.0.0.0:*",process:"sshd"},{protocol:"tcp",state:"ESTAB",localAddress:"10.0.0.2:443",peerAddress:"10.0.0.8:51000",process:"nginx"}],warning:null});vi.spyOn(api,"startNetworkDiagnostic").mockResolvedValue(task);vi.spyOn(api,"onBackgroundTask").mockResolvedValue(()=>undefined);vi.spyOn(api,"getTask").mockResolvedValue(task);});it("shows sockets and runs a cancellable ping task",async()=>{const user=userEvent.setup();render(<NetworkDiagnostics sessionId="session-1" onError={vi.fn()}/>);expect(await screen.findByText("0.0.0.0:22")).toBeInTheDocument();await user.type(screen.getByRole("textbox",{name:"网络诊断目标"}),"example.com");await user.click(screen.getByRole("button",{name:"Ping"}));await waitFor(()=>expect(api.startNetworkDiagnostic).toHaveBeenCalledWith("session-1","ping","example.com"));expect(await screen.findByText(/Ping · example.com/)).toBeInTheDocument();expect(screen.getByText(/20.0\/30.0/)).toBeInTheDocument();});it("filters sockets by localized state and address or process",async()=>{const user=userEvent.setup();render(<NetworkDiagnostics sessionId="session-1" onError={vi.fn()}/>);expect(await screen.findByText("nginx")).toBeVisible();await user.selectOptions(screen.getByRole("combobox",{name:"连接状态筛选"}),"LISTEN");expect(screen.getAllByText("监听")).toHaveLength(2);expect(screen.queryByText("nginx")).not.toBeInTheDocument();await user.selectOptions(screen.getByRole("combobox",{name:"连接状态筛选"}),"all");await user.type(screen.getByRole("textbox",{name:"搜索端口与连接"}),"nginx");expect(screen.getByText("显示 1/1 条，共 2 条")).toBeVisible();expect(screen.getByText("10.0.0.2:443")).toBeVisible();expect(screen.queryByText("0.0.0.0:22")).not.toBeInTheDocument();});it("renders large socket reports in bounded batches",async()=>{const user=userEvent.setup();vi.mocked(api.networkSockets).mockResolvedValueOnce({items:Array.from({length:205},(_,index)=>({protocol:"tcp",state:"ESTAB",localAddress:`10.0.0.1:${10000+index}`,peerAddress:`10.0.0.2:${20000+index}`,process:`process-${index}`})),warning:null});render(<NetworkDiagnostics sessionId="session-1" onError={vi.fn()}/>);expect(await screen.findByText("process-199")).toBeVisible();expect(screen.queryByText("process-204")).not.toBeInTheDocument();expect(screen.getByText("显示 200/205 条，共 205 条")).toBeVisible();await user.click(screen.getByRole("button",{name:/继续显示 200 条/}));expect(screen.getByText("process-204")).toBeVisible();expect(screen.getByText("显示 205/205 条，共 205 条")).toBeVisible();});});
