import { Activity,LoaderCircle,Network,RefreshCw,Route,Send,Square } from "lucide-react";
import { useCallback,useEffect,useState } from "react";
import { api } from "../../lib/api";
import { waitForTask } from "../../lib/background-task";
import { errorMessage } from "../../lib/format";
import type { BackgroundTask,NetworkDiagnosticResult,NetworkSocketReport } from "../../types";
import "./MonitorTools.css";

export function NetworkDiagnostics({sessionId,onError}:{sessionId:string;onError:(message:string)=>void}){
  const[sockets,setSockets]=useState<NetworkSocketReport|null>(null);const[loading,setLoading]=useState(true);const[target,setTarget]=useState("");const[task,setTask]=useState<BackgroundTask|null>(null);const[result,setResult]=useState<NetworkDiagnosticResult|null>(null);const[pingHistory,setPingHistory]=useState<{time:number;latency:number}[]>([]);
  const load=useCallback(()=>{setLoading(true);api.networkSockets(sessionId).then(setSockets).catch((error)=>onError(errorMessage(error))).finally(()=>setLoading(false));},[onError,sessionId]);useEffect(()=>{void load();},[load]);
  const run=async(kind:"ping"|"traceroute")=>{if(!target.trim())return;try{const started=await api.startNetworkDiagnostic(sessionId,kind,target.trim());setTask(started);const value=await waitForTask(started) as NetworkDiagnosticResult;setResult(value);if(kind==="ping"){const latency=parseAverageLatency(value.output);if(latency!=null)setPingHistory((current)=>[...current,{time:Date.now(),latency}].slice(-20));}}catch(error){if((error as DOMException).name!=="AbortError")onError(errorMessage(error));}finally{setTask(null);}};
  return <section className="network-diagnostics"><div className="section-heading"><div><h3><Network size={15}/>端口与连接</h3><p>{sockets?.items.length??0} 条，最多显示 5000 条</p></div><button className="mini-button" onClick={()=>void load()} disabled={loading}><RefreshCw size={12}/>刷新</button></div>{sockets?.warning&&<div className="inline-warning">{sockets.warning}</div>}{loading?<div className="loading-state"><LoaderCircle className="spin"/>读取远端连接…</div>:<div className="socket-table"><header><span>协议</span><span>状态</span><span>本地地址</span><span>对端地址</span><span>进程</span></header>{sockets?.items.slice(0,5000).map((socket,index)=><div key={`${index}-${socket.protocol}-${socket.localAddress}`}><code>{socket.protocol}</code><span>{socket.state}</span><code>{socket.localAddress}</code><code>{socket.peerAddress}</code><span title={socket.process}>{socket.process||"—"}</span></div>)}</div>}<div className="diagnostic-runner"><form onSubmit={(event)=>{event.preventDefault();void run("ping");}}><input value={target} onChange={(event)=>setTarget(event.target.value)} placeholder="主机名或 IP 地址" aria-label="网络诊断目标"/><button className="button secondary" disabled={!target.trim()||Boolean(task)}><Activity size={14}/>Ping</button><button type="button" className="button secondary" disabled={!target.trim()||Boolean(task)} onClick={()=>void run("traceroute")}><Route size={14}/>Trace</button>{task&&<button type="button" className="button secondary" onClick={()=>void api.cancelTask(task.id)}><Square size={12}/>取消</button>}</form>{pingHistory.length>1&&<PingTrend samples={pingHistory}/>} {result&&<div className="diagnostic-output"><header><strong>{result.kind==="ping"?"Ping":"Traceroute"} · {result.target}</strong><span>{result.durationMs} ms</span></header><pre>{result.output}</pre></div>}</div></section>;
}
function parseAverageLatency(output:string):number|null{const match=output.match(/=\s*[\d.]+\/([\d.]+)\/[\d.]+/);return match?Number(match[1]):null;}
function PingTrend({samples}:{samples:{time:number;latency:number}[]}){const max=Math.max(1,...samples.map((sample)=>sample.latency));const points=samples.map((sample,index)=>`${index/(samples.length-1)*100},${28-sample.latency/max*24}`).join(" ");return <div className="ping-trend"><span><Send size={12}/>Ping 历史 · {samples.at(-1)?.latency.toFixed(1)} ms</span><svg viewBox="0 0 100 30" preserveAspectRatio="none" role="img" aria-label="Ping 延迟历史趋势"><polyline points={points}/></svg></div>;}
