import { Clipboard, Download, LoaderCircle, RefreshCw, ServerCog } from "lucide-react";
import { save } from "@tauri-apps/plugin-dialog";
import { useCallback, useEffect, useState } from "react";
import { api } from "../../lib/api";
import type { SystemInfo } from "../../types";
import { IconButton } from "../../components/IconButton";
import { errorMessage, formatBytes } from "../../lib/format";
import { useAppStore } from "../../store/app-store";

export function SystemInfoPanel({sessionId}:{sessionId:string}){const[info,setInfo]=useState<SystemInfo|null>(null);const[loading,setLoading]=useState(true);const{setError}=useAppStore();const load=useCallback(()=>{setLoading(true);api.systemInfo(sessionId).then(setInfo).catch((reason)=>setError(errorMessage(reason))).finally(()=>setLoading(false));},[sessionId,setError]);useEffect(()=>{load();},[load]);if(loading)return <div className="loading-state"><LoaderCircle className="spin"/>读取系统信息…</div>;if(!info)return <div className="empty-files"><ServerCog size={28}/>无法读取系统信息</div>;const text=JSON.stringify(info,null,2);const exportInfo=async()=>{const path=await save({defaultPath:`${info.hostname}-system-info.json`});if(path)try{await api.exportSystemInfo(sessionId,path);}catch(error){setError(errorMessage(error));}};return <div className="system-info"><div className="system-info-toolbar"><strong>{info.hostname}</strong><span>{info.os}</span><IconButton icon={RefreshCw} label="刷新系统信息" onClick={load}/><IconButton icon={Clipboard} label="复制系统信息" onClick={()=>navigator.clipboard.writeText(text)}/><IconButton icon={Download} label="导出系统信息" onClick={exportInfo}/></div><div className="info-cards"><Info label="内核" value={info.kernel}/><Info label="架构" value={info.architecture}/><Info label="CPU" value={`${info.cpuModel} · ${info.cpuCores} 核`}/><Info label="内存" value={formatBytes(info.memoryTotalBytes)}/></div><h3>网络接口</h3><table><thead><tr><th>名称</th><th>地址</th></tr></thead><tbody>{info.interfaces.map((item)=><tr key={item.name}><td>{item.name}</td><td>{item.addresses.join(", ")}</td></tr>)}</tbody></table><h3>文件系统</h3><table><thead><tr><th>设备</th><th>挂载点</th><th>大小</th><th>已用</th><th>可用</th></tr></thead><tbody>{info.disks.map((disk)=><tr key={`${disk.filesystem}-${disk.mountPoint}`}><td>{disk.filesystem}</td><td>{disk.mountPoint}</td><td>{formatBytes(disk.totalBytes)}</td><td>{formatBytes(disk.usedBytes)} ({disk.usedPercent.toFixed(0)}%)</td><td>{formatBytes(disk.availableBytes)}</td></tr>)}</tbody></table></div>}
function Info({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value||"—"}</strong></div>}
