import { ChevronRight, CircleOff, Clock3, Copy, Download, Edit3, Folder, FolderInput, Monitor, MoreHorizontal, Network, Plus, RotateCcw, Search, Server, Share, ShieldAlert, Stethoscope, TerminalSquare, Trash2 } from "lucide-react";
import { open, save } from "@tauri-apps/plugin-dialog";
import { useCallback, useMemo, useState, useEffect } from "react";
import { api } from "../../lib/api";
import { useAppStore } from "../../store/app-store";
import type { ConnectionProfile, Folder as FolderModel } from "../../types";
import { IconButton } from "../../components/IconButton";
import { errorMessage } from "../../lib/format";
import { TunnelManager } from "./TunnelManager";
import { ConnectionDiagnostics } from "./ConnectionDiagnostics";
import { ConnectionFolderTree } from "./ConnectionFolderTree";

export function ConnectionSidebar({ connect }: { connect: (profile: ConnectionProfile) => Promise<void> }) {
  const { connections, openConnectionEditor, refreshConnections, setError } = useAppStore();
  const [query, setQuery] = useState(""); const [menuId, setMenuId] = useState<string|null>(null);
  const [tunnelConnection,setTunnelConnection]=useState<ConnectionProfile|null>(null);
  const [diagnosticConnection,setDiagnosticConnection]=useState<ConnectionProfile|null>(null);
  const [folders,setFolders]=useState<FolderModel[]>([]);const[expandedFolders,setExpandedFolders]=useState(()=>new Set<string>());const[deleted,setDeleted]=useState<ConnectionProfile[]>([]);const[connectionOrder,setConnectionOrder]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("cnshell-connection-order")??"[]");}catch{return[];}});const[folderFilter,setFolderFilter]=useState<string|"all"|"recent"|"ungrouped"|"trash">("all");const[protocolFilter,setProtocolFilter]=useState<"all"|"ssh"|"rdp"|"local">("all");
  const loadFolders=useCallback(()=>api.listFolders().then(setFolders).catch((error)=>setError(errorMessage(error))),[setError]);useEffect(()=>{void loadFolders();},[loadFolders]);
  const loadDeleted=useCallback(()=>api.listDeletedConnections().then(setDeleted).catch((error)=>setError(errorMessage(error))),[setError]);useEffect(()=>{if(folderFilter==="trash")void loadDeleted();},[folderFilter,loadDeleted]);
  const filtered = useMemo(() => (folderFilter==="trash"?deleted:connections).filter((item) => `${item.name} ${item.host} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())).filter((item)=>protocolFilter==="all"||item.protocol===protocolFilter).filter((item)=>folderFilter==="trash"||folderFilter==="all"||folderFilter==="recent"&&Boolean(item.lastConnectedAt)||folderFilter==="ungrouped"&&!item.folderId||item.folderId===folderFilter).sort((a,b)=>{if(folderFilter==="recent")return(b.lastConnectedAt??"").localeCompare(a.lastConnectedAt??"");const aIndex=connectionOrder.indexOf(a.id),bIndex=connectionOrder.indexOf(b.id);if(aIndex>=0||bIndex>=0)return(aIndex<0?Number.MAX_SAFE_INTEGER:aIndex)-(bIndex<0?Number.MAX_SAFE_INTEGER:bIndex);return a.name.localeCompare(b.name,"zh-CN");}), [connections,deleted,query,folderFilter,protocolFilter,connectionOrder]);
  useEffect(()=>{localStorage.setItem("cnshell-connection-order",JSON.stringify(connectionOrder));},[connectionOrder]);
  const renameFolder=async(folder:FolderModel)=>{const name=prompt("重命名文件夹",folder.name);if(!name)return;try{await api.saveFolder(folder.id,name,folder.parentId);await loadFolders();}catch(error){setError(errorMessage(error));}};
  const deleteFolder=async(folder:FolderModel)=>{if(!confirm(`删除文件夹“${folder.name}”及其全部子文件夹？其中连接会移到未分组。`))return;try{await api.deleteFolder(folder.id);setFolderFilter("all");await Promise.all([loadFolders(),refreshConnections()]);}catch(error){setError(errorMessage(error));}};
  const dropConnection=async(event:React.DragEvent,folderId:string|null)=>{event.preventDefault();const id=event.dataTransfer.getData("text/cnshell-connection");if(!id)return;try{await api.moveConnection(id,folderId);await refreshConnections();}catch(error){setError(errorMessage(error));}};
  const reorderConnection=(event:React.DragEvent,targetId:string)=>{event.preventDefault();event.stopPropagation();const sourceId=event.dataTransfer.getData("text/cnshell-connection");if(!sourceId||sourceId===targetId)return;setConnectionOrder(()=>{const order=connections.map((item)=>item.id).filter((id)=>id!==sourceId);const targetIndex=order.indexOf(targetId);order.splice(targetIndex<0?order.length:targetIndex,0,sourceId);return order;});};
  const remove = async (connection: ConnectionProfile) => { if (!confirm(`将“${connection.name}”移到已删除项目？已打开会话不会断开。`)) return; try { await api.deleteConnection(connection.id);setMenuId(null);await Promise.all([refreshConnections(),loadDeleted()]); } catch (error) { setError(errorMessage(error)); } };
  const restore=async(connection:ConnectionProfile)=>{try{await api.restoreConnection(connection.id);setMenuId(null);await Promise.all([refreshConnections(),loadDeleted()]);}catch(error){setError(errorMessage(error));}};
  const purge=async(connection:ConnectionProfile)=>{if(!confirm(`永久删除“${connection.name}”及其 Keychain 凭据？此操作无法撤销。`))return;try{await api.purgeConnection(connection.id);setMenuId(null);await loadDeleted();}catch(error){setError(errorMessage(error));}};
  const duplicate=async(connection:ConnectionProfile)=>{try{await api.duplicateConnection(connection.id,crypto.randomUUID());setMenuId(null);await refreshConnections();}catch(error){setError(errorMessage(error));}};
  const folderPath=(folder:FolderModel)=>{const names=[folder.name];let parent=folder.parentId;const seen=new Set([folder.id]);while(parent){const match=folders.find((item)=>item.id===parent);if(!match||seen.has(match.id))break;seen.add(match.id);names.unshift(match.name);parent=match.parentId;}return names.join(" / ");};
  const move=async(connection:ConnectionProfile)=>{const choices=["0：未分组",...folders.map((folder,index)=>`${index+1}：${folderPath(folder)}`)];const answer=prompt(`移动到文件夹：\n${choices.join("\n")}`,String(Math.max(0,folders.findIndex((folder)=>folder.id===connection.folderId)+1)));if(answer==null)return;const index=Number(answer);if(!Number.isInteger(index)||index<0||index>folders.length){setError("请输入列表中的文件夹编号");return;}try{await api.moveConnection(connection.id,index===0?null:folders[index-1].id);setMenuId(null);await refreshConnections();}catch(error){setError(errorMessage(error));}};
  const exportOne=async(connection:ConnectionProfile)=>{try{const path=await save({defaultPath:`${connection.name}.cnshell.json`});if(!path)return;await api.exportConnection(connection.id,path);setMenuId(null);}catch(error){setError(errorMessage(error));}};
  const importConnections=async()=>{if(!api.isDesktop()){setError("导入需要运行 CNshell 桌面版");return;}const path=await open({multiple:false,filters:[{name:"CNshell 备份",extensions:["json"]}]});if(!path)return;try{await api.importConnections(path);await refreshConnections();}catch(error){const message=errorMessage(error);if(!message.includes("口令")){setError(message);return;}const passphrase=prompt("该备份已加密，请输入导出口令")??undefined;try{await api.importConnections(path,passphrase);await refreshConnections();}catch(retry){setError(errorMessage(retry));}}};
  const toggleFolder=(id:string)=>setExpandedFolders((current)=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
  return <aside className="connections-sidebar">
    <div className="sidebar-title"><div><span className="eyebrow">工作区</span><h1>连接</h1></div><div className="sidebar-actions"><IconButton icon={Download} label="导入连接" onClick={()=>void importConnections()}/><IconButton icon={Plus} label="新建连接" onClick={() => openConnectionEditor()} /></div></div>
    <label className="search-box"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索主机、标签…" aria-label="搜索连接"/></label>
    <div className="folder-toolbar"><button className={folderFilter==="all"?"active":""} onClick={()=>setFolderFilter("all")}><Folder size={14}/>所有连接<span>{connections.length}</span></button><button className={folderFilter==="recent"?"active":""} onClick={()=>setFolderFilter("recent")}><Clock3 size={14}/>最近连接</button><select aria-label="协议筛选" value={protocolFilter} onChange={(event)=>setProtocolFilter(event.target.value as typeof protocolFilter)}><option value="all">全部</option><option value="ssh">SSH</option><option value="rdp">RDP</option><option value="local">本地 Shell</option></select></div>
    <div className="folder-list"><button className={folderFilter==="ungrouped"?"active":""} onClick={()=>setFolderFilter("ungrouped")} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>void dropConnection(event,null)}><Folder size={13}/>未分组</button><ConnectionFolderTree folders={folders} activeId={folderFilter} expanded={expandedFolders} counts={new Map(folders.map((folder)=>[folder.id,connections.filter((item)=>item.folderId===folder.id).length]))} onSelect={setFolderFilter} onToggle={toggleFolder} onRename={(folder)=>void renameFolder(folder)} onDelete={(folder)=>void deleteFolder(folder)} onDropConnection={(event,id)=>void dropConnection(event,id)}/><button className={folderFilter==="trash"?"active":""} onClick={()=>setFolderFilter("trash")}><Trash2 size={13}/>已删除项目<span>{deleted.length||""}</span></button></div>
    <div className="connection-list" role="list">
      {filtered.map((connection) => <div className="connection-row" key={connection.id} role="listitem" draggable={folderFilter!=="trash"} onDragStart={(event)=>{event.dataTransfer.setData("text/cnshell-connection",connection.id);event.dataTransfer.effectAllowed="move";}} onDragOver={(event)=>{if(folderFilter!=="trash")event.preventDefault();}} onDrop={(event)=>reorderConnection(event,connection.id)} onDoubleClick={() => folderFilter!=="trash"&&connect(connection)} onContextMenu={(event)=>{event.preventDefault();setMenuId(connection.id);}}>
        <button className="connection-main" aria-disabled={folderFilter==="trash"} onClick={() => folderFilter!=="trash"&&connect(connection)}>
          <span className={`protocol-icon ${connection.protocol}`}><>{connection.protocol === "ssh" ? <Server size={17}/> : connection.protocol === "rdp" ? <Monitor size={17}/> : <TerminalSquare size={17}/>}</></span>
          <span className="connection-copy"><strong>{connection.name}</strong><small>{connection.protocol === "local" ? `${connection.username} · 本机默认 Shell` : `${connection.username}@${connection.host}:${connection.port}`}</small></span>
          <ChevronRight size={14}/>
        </button>
        <IconButton icon={MoreHorizontal} label={`${connection.name}操作`} onClick={() => setMenuId(menuId === connection.id ? null : connection.id)} />
        {menuId === connection.id && <div className="context-menu">{folderFilter==="trash"?<><button onClick={()=>void restore(connection)}><RotateCcw size={14}/>恢复</button><button onClick={()=>void purge(connection)} className="danger"><Trash2 size={14}/>永久删除</button></>:<><button onClick={() => { openConnectionEditor(connection); setMenuId(null); }}><Edit3 size={14}/>编辑</button><button onClick={()=>void duplicate(connection)}><Copy size={14}/>复制连接</button><button onClick={()=>void move(connection)}><FolderInput size={14}/>移动到文件夹</button><button onClick={()=>void exportOne(connection)}><Share size={14}/>安全导出</button>{connection.protocol==="ssh"&&<><button onClick={()=>{setDiagnosticConnection(connection);setMenuId(null);}}><Stethoscope size={14}/>连接诊断</button><button onClick={()=>{setTunnelConnection(connection);setMenuId(null);}}><Network size={14}/>端口转发</button></>}<button onClick={() => remove(connection)} className="danger"><Trash2 size={14}/>删除</button></>}</div>}
      </div>)}
      {!filtered.length && <div className="empty-sidebar"><CircleOff size={24}/><span>没有匹配的连接</span><button onClick={() => openConnectionEditor()}>新建连接</button></div>}
    </div>
    <div className="security-note"><ShieldAlert size={15}/><span>主机指纹严格校验 · 凭据存于 Keychain</span></div>
    {tunnelConnection&&<TunnelManager connection={tunnelConnection} onClose={()=>setTunnelConnection(null)} onError={setError}/>}
    {diagnosticConnection&&<ConnectionDiagnostics connection={diagnosticConnection} onClose={()=>setDiagnosticConnection(null)} onError={setError}/>}
  </aside>;
}
