import { Command, File, Folder, History, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";
import type { CommandSnippet, TerminalSession } from "../../types";
import { workspaceRuntime } from "../../lib/workspace-runtime";
import { completionToken, pathLookup, rankCommandSuggestions, replaceCompletionToken, shellQuote, type CommandSuggestion } from "./smart-command";

export function SmartCommandEntry({session,snippets,history,draft,setDraft,onRun,onSave}:{session:TerminalSession;snippets:CommandSnippet[];history:string[];draft:string;setDraft:(value:string)=>void;onRun:(command:string)=>void;onSave:()=>void}){
  const[pathSuggestions,setPathSuggestions]=useState<CommandSuggestion[]>([]);const[open,setOpen]=useState(false);const[active,setActive]=useState(-1);
  const suggestions=useMemo(()=>{if(draft.trim().length<3)return pathSuggestions;const staticItems:CommandSuggestion[]=[...history.map((command,index)=>({id:`history-${index}-${command}`,kind:"history" as const,label:command,detail:"最近命令",value:command})),...snippets.map((snippet)=>({id:`snippet-${snippet.id}`,kind:"snippet" as const,label:snippet.name,detail:snippet.command,value:snippet.command}))];return[...pathSuggestions,...rankCommandSuggestions(draft,staticItems,10-pathSuggestions.length)];},[draft,history,pathSuggestions,snippets]);
  useEffect(()=>{const lookup=pathLookup(draft,workspaceRuntime.cwdBySession.get(session.id)??"/");if(!lookup){setPathSuggestions([]);return;}let cancelled=false;const timer=window.setTimeout(()=>{void api.listFiles(session.id,lookup.parent,false).then((files)=>{if(cancelled)return;const matches=files.filter((file)=>file.name.toLocaleLowerCase("zh-CN").startsWith(lookup.prefix.toLocaleLowerCase("zh-CN"))).slice(0,6).map((file)=>({id:`path-${file.path}`,kind:"path" as const,label:file.name,detail:file.kind==="directory"?"远端目录":"远端文件",value:file.path}));setPathSuggestions(matches);}).catch(()=>{if(!cancelled)setPathSuggestions([]);});},80);return()=>{cancelled=true;window.clearTimeout(timer);};},[draft,session.id]);
  useEffect(()=>{setActive(-1);setOpen(Boolean(draft.trim()&&suggestions.length));},[draft,suggestions.length]);
  const choose=(suggestion:CommandSuggestion)=>{setDraft(suggestion.kind==="path"?replaceCompletionToken(draft,shellQuote(suggestion.value)):suggestion.value);setOpen(false);setActive(-1);};
  return <div className="smart-command"><form className="command-entry" onSubmit={(event)=>{event.preventDefault();if(open&&active>=0&&suggestions[active])choose(suggestions[active]);else if(draft.trim())onRun(draft.trim());}}><Command size={15}/><input role="combobox" aria-label="智能命令输入" aria-expanded={open} aria-controls="command-suggestions" aria-activedescendant={active>=0?`command-suggestion-${active}`:undefined} autoComplete="off" value={draft} onFocus={()=>setOpen(Boolean(draft.trim()&&suggestions.length))} onChange={(event)=>setDraft(event.target.value)} onKeyDown={(event)=>{if(!open||!suggestions.length)return;if(event.key==="ArrowDown"){event.preventDefault();setActive((value)=>(value+1)%suggestions.length);}else if(event.key==="ArrowUp"){event.preventDefault();setActive((value)=>(value-1+suggestions.length)%suggestions.length);}else if(event.key==="Escape"){event.preventDefault();setOpen(false);}else if(event.key==="Tab"&&active>=0&&suggestions[active]){event.preventDefault();choose(suggestions[active]);}}} placeholder="输入命令、快捷命令或远端路径"/><button type="button" className="mini-button" disabled={!draft.trim()} onClick={onSave}><Save size={13}/>保存</button><button className="button primary" disabled={!draft.trim()}>执行</button></form>{open&&<div id="command-suggestions" className="command-suggestions" role="listbox" aria-label="命令建议">{suggestions.map((suggestion,index)=><button id={`command-suggestion-${index}`} type="button" role="option" aria-selected={active===index} className={active===index?"active":""} key={suggestion.id} onPointerDown={(event)=>event.preventDefault()} onClick={()=>choose(suggestion)}>{suggestion.kind==="history"?<History size={14}/>:suggestion.kind==="path"?(suggestion.detail==="远端目录"?<Folder size={14}/>:<File size={14}/>):<Command size={14}/>}<span><strong>{suggestion.label}</strong><small>{suggestion.detail}</small></span>{suggestion.kind==="path"&&<code>{completionToken(draft)?.value}</code>}</button>)}</div>}</div>;
}
