import { describe,expect,it } from "vitest";
import { completionToken, fuzzyScore, isHighRiskCommand, pathLookup, rankCommandSuggestions, renderCommandTemplate, replaceCompletionToken, shellQuote, templateParameters, type CommandSuggestion } from "./smart-command";

describe("smart command",()=>{
  it("ranks prefix and fuzzy matches",()=>{const items:CommandSuggestion[]=[{id:"1",kind:"history",label:"systemctl status nginx",detail:"",value:""},{id:"2",kind:"snippet",label:"查看日志",detail:"journalctl",value:""}];expect(fuzzyScore("sys","systemctl")).toBeGreaterThan(fuzzyScore("stl","systemctl")!);expect(rankCommandSuggestions("sys",items)[0].id).toBe("1");});
  it("replaces only the active shell token",()=>{expect(completionToken("cat /et")).toEqual({start:4,value:"/et"});expect(completionToken("cat '/目录/有 空格")).toEqual({start:4,value:"'/目录/有 空格"});expect(completionToken("cat /目录/有\\ 空格")).toEqual({start:4,value:"/目录/有\\ 空格"});expect(replaceCompletionToken("cat /et",shellQuote("/etc/hosts"))).toBe("cat '/etc/hosts'");expect(pathLookup("cat ./lo","/var")).toEqual({parent:"/var/.",prefix:"lo"});expect(pathLookup("cat '/目录/有 空格","/")).toEqual({parent:"/目录",prefix:"有 空格"});expect(pathLookup("cat /目录/有\\ 空格","/")).toEqual({parent:"/目录",prefix:"有 空格"});});
  it("quotes every template parameter",()=>{expect(templateParameters("systemctl {{action}} {{service}} {{service}}")).toEqual(["action","service"]);expect(renderCommandTemplate("printf %s {{value}}",{value:"a'; rm -rf /"})).toBe("printf %s 'a'\\''; rm -rf /'");expect(()=>renderCommandTemplate("echo {{missing}}",{})).toThrow("缺少参数");});
  it("detects destructive commands without blocking normal reads",()=>{expect(isHighRiskCommand("rm -rf /")).toBe(true);expect(isHighRiskCommand("dd if=x of=/dev/disk2")).toBe(true);expect(isHighRiskCommand("rm -rf ./build")).toBe(false);expect(isHighRiskCommand("df -h")).toBe(false);});
  it("ranks a large local suggestion set within the interaction budget",()=>{const items=Array.from({length:2_000},(_,index)=>({id:String(index),kind:"history" as const,label:`systemctl status service-${index}`,detail:"最近命令",value:""}));const started=performance.now();expect(rankCommandSuggestions("sys",items,10)).toHaveLength(10);expect(performance.now()-started).toBeLessThan(100);});
});
