export type SplitDirection="horizontal"|"vertical";
export type TerminalLayout={type:"leaf";sessionId:string}|{type:"split";id:string;direction:SplitDirection;ratio:number;first:TerminalLayout;second:TerminalLayout};

export const leaf=(sessionId:string):TerminalLayout=>({type:"leaf",sessionId});
export function layoutSessions(layout:TerminalLayout):string[]{return layout.type==="leaf"?[layout.sessionId]:[...layoutSessions(layout.first),...layoutSessions(layout.second)];}
export function splitLeaf(layout:TerminalLayout,target:string,sessionId:string,direction:SplitDirection):TerminalLayout{if(layout.type==="leaf")return layout.sessionId===target?{type:"split",id:crypto.randomUUID(),direction,ratio:.5,first:layout,second:leaf(sessionId)}:layout;return{...layout,first:splitLeaf(layout.first,target,sessionId,direction),second:splitLeaf(layout.second,target,sessionId,direction)};}
export function removeLeaf(layout:TerminalLayout,sessionId:string):TerminalLayout|null{if(layout.type==="leaf")return layout.sessionId===sessionId?null:layout;const first=removeLeaf(layout.first,sessionId),second=removeLeaf(layout.second,sessionId);if(!first)return second;if(!second)return first;return{...layout,first,second};}
export function updateRatio(layout:TerminalLayout,id:string,ratio:number):TerminalLayout{if(layout.type==="leaf")return layout;if(layout.id===id)return{...layout,ratio:clampRatio(ratio)};return{...layout,first:updateRatio(layout.first,id,ratio),second:updateRatio(layout.second,id,ratio)};}
export function mapLayoutSessions(layout:TerminalLayout,map:Map<string,string>):TerminalLayout|null{if(layout.type==="leaf"){const sessionId=map.get(layout.sessionId);return sessionId?leaf(sessionId):null;}const first=mapLayoutSessions(layout.first,map),second=mapLayoutSessions(layout.second,map);if(!first)return second;if(!second)return first;return{...layout,ratio:clampRatio(layout.ratio),first,second};}
export function validateLayout(value:unknown,available:Set<string>):TerminalLayout|null{if(!value||typeof value!=="object")return null;const node=value as Partial<TerminalLayout>;if(node.type==="leaf"&&typeof node.sessionId==="string"&&available.has(node.sessionId))return leaf(node.sessionId);if(node.type==="split"&&typeof node.id==="string"&&(node.direction==="horizontal"||node.direction==="vertical")){const split=node as Extract<TerminalLayout,{type:"split"}>;const first=validateLayout(split.first,available),second=validateLayout(split.second,available);if(!first)return second;if(!second)return first;return{type:"split",id:split.id,direction:split.direction,ratio:clampRatio(Number(split.ratio)),first,second};}return null;}
export const clampRatio=(ratio:number)=>Math.min(.8,Math.max(.2,Number.isFinite(ratio)?ratio:.5));

export type TerminalRect={sessionId:string;left:number;top:number;width:number;height:number};
export function layoutRects(layout:TerminalLayout,left=0,top=0,width=100,height=100):TerminalRect[]{if(layout.type==="leaf")return[{sessionId:layout.sessionId,left,top,width,height}];if(layout.direction==="vertical"){const firstWidth=width*layout.ratio;return[...layoutRects(layout.first,left,top,firstWidth,height),...layoutRects(layout.second,left+firstWidth,top,width-firstWidth,height)];}const firstHeight=height*layout.ratio;return[...layoutRects(layout.first,left,top,width,firstHeight),...layoutRects(layout.second,left,top+firstHeight,width,height-firstHeight)];}
