import { Download, KeyRound, Plus, ShieldAlert, Trash2, Upload } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { open, save } from "@tauri-apps/plugin-dialog";
import { api } from "../../lib/api";
import { errorMessage } from "../../lib/format";
import type { ConnectionProfile, ProxyProfile, ProxyType, SaveProxyInput } from "../../types";
import { IconButton } from "../../components/IconButton";
import { FeedbackSettings } from "./FeedbackSettings";
import { usePlatformCapabilities } from "../../lib/platform";

export function AdvancedSettings({ connections, onChanged, onError }: { connections: ConnectionProfile[]; onChanged: () => Promise<void>; onError: (message: string) => void }) {
  const platform=usePlatformCapabilities();
  const [proxies,setProxies]=useState<ProxyProfile[]>([]);const[editing,setEditing]=useState<SaveProxyInput|null>(null);
  const load=useCallback(()=>api.listProxies().then(setProxies).catch((error)=>onError(errorMessage(error))),[onError]);useEffect(()=>{void load();},[load]);
  const add=(type:ProxyType)=>setEditing({id:crypto.randomUUID(),name:"",type,host:"",port:type==="http"?8080:1080,username:null,jumpConnectionId:null,credential:""});
  const submit=async()=>{if(!editing)return;try{await api.saveProxy(editing);setEditing(null);await load();}catch(error){onError(errorMessage(error));}};
  const exportData=async(includeSecrets:boolean)=>{if(!api.isDesktop()){onError("导出需要运行桌面版");return;}const path=await save({defaultPath:"CNshell-connections.cnshell.json"});if(!path)return;const passphrase=includeSecrets?prompt("输入至少 8 位导出口令。该口令无法找回。")??undefined:undefined;try{await api.exportConnections(path,includeSecrets,passphrase);}catch(error){onError(errorMessage(error));}};
  const importData=async()=>{if(!api.isDesktop()){onError("导入需要运行桌面版");return;}const path=await open({multiple:false,filters:[{name:"CNshell 备份",extensions:["json"]}]});if(!path)return;let passphrase: string|undefined;try{await api.importConnections(path,passphrase);await onChanged();}catch(error){const message=errorMessage(error);if(message.includes("口令")){passphrase=prompt("该备份已加密，请输入导出口令")??undefined;try{await api.importConnections(path,passphrase);await onChanged();}catch(retry){onError(errorMessage(retry));}}else onError(message);}};
  return <div className="advanced-settings"><section><div className="section-heading"><h3><KeyRound size={16}/>代理与跳板机</h3><div><button className="mini-button" onClick={()=>add("socks5")}><Plus size={13}/>SOCKS5</button><button className="mini-button" onClick={()=>add("http")}><Plus size={13}/>HTTP</button><button className="mini-button" onClick={()=>add("sshJump")}><Plus size={13}/>SSH 跳板</button></div></div>{proxies.map((proxy)=><div className="proxy-row" key={proxy.id}><div><strong>{proxy.name}</strong><small>{proxy.type==="sshJump"?`跳板连接：${connections.find((item)=>item.id===proxy.jumpConnectionId)?.name??"未选择"}`:`${proxy.host}:${proxy.port}`}</small></div><IconButton icon={Trash2} label={`删除 ${proxy.name}`} onClick={()=>api.deleteProxy(proxy.id).then(load).catch((error)=>onError(errorMessage(error)))}/></div>)}{!proxies.length&&!editing&&<p className="muted-copy">未配置代理，连接将直接访问服务器。</p>}{editing&&<div className="proxy-form"><label><span>名称</span><input value={editing.name} onChange={(event)=>setEditing({...editing,name:event.target.value})}/></label>{editing.type==="sshJump"?<label><span>跳板连接</span><select value={editing.jumpConnectionId??""} onChange={(event)=>setEditing({...editing,jumpConnectionId:event.target.value||null})}><option value="">选择 SSH 连接</option>{connections.filter((item)=>item.protocol==="ssh").map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:<><label><span>主机</span><input value={editing.host} onChange={(event)=>setEditing({...editing,host:event.target.value})}/></label><label><span>端口</span><input type="number" value={editing.port} onChange={(event)=>setEditing({...editing,port:Number(event.target.value)})}/></label><label><span>用户名（可选）</span><input value={editing.username??""} onChange={(event)=>setEditing({...editing,username:event.target.value||null})}/></label><label><span>密码（{platform.credentialStoreName}）</span><input type="password" value={editing.credential??""} onChange={(event)=>setEditing({...editing,credential:event.target.value})}/></label></>}<div className="form-actions"><button className="button secondary" onClick={()=>setEditing(null)}>取消</button><button className="button primary" onClick={submit}>保存代理</button></div></div>}</section><section><h3><ShieldAlert size={16}/>连接库备份</h3><p className="muted-copy">普通导出不包含密码。包含凭据的备份使用 Argon2id 与 AES-256-GCM 加密。</p><div className="backup-actions"><button className="button secondary" onClick={()=>exportData(false)}><Upload size={14}/>安全导出</button><button className="button secondary" onClick={()=>exportData(true)}><KeyRound size={14}/>加密导出凭据</button><button className="button secondary" onClick={importData}><Download size={14}/>导入备份</button></div></section><FeedbackSettings onError={onError}/></div>;
}
