import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { api } from "../../lib/api";
import type { ConnectionProfile } from "../../types";
import { OpenSshTools } from "./OpenSshTools";

const dialog=vi.hoisted(()=>({open:vi.fn(),save:vi.fn()}));vi.mock("@tauri-apps/plugin-dialog",()=>dialog);
const existing:ConnectionProfile={id:"existing",folderId:null,protocol:"ssh",name:"已有",host:"10.0.0.1",port:22,username:"root",authType:"sshAgent",privateKeyPath:null, certificatePath: null,hostKeyPolicy:"strict",note:"",tags:[],encoding:"UTF-8",startupCommand:null,proxyId:null,environment:{},hasCredential:false,createdAt:"",updatedAt:"",lastConnectedAt:null};
describe("OpenSshTools",()=>{beforeEach(()=>{vi.restoreAllMocks();dialog.open.mockResolvedValue("/Users/test/.ssh/config");dialog.save.mockReset();vi.spyOn(api,"importOpenSshConfig").mockResolvedValue([{alias:"duplicate",hostname:"10.0.0.1",user:"root",port:22,identityFile:null,proxyJump:null,source:"config",warnings:[]},{alias:"new-host",hostname:"10.0.0.2",user:"ubuntu",port:2222,identityFile:"/Users/test/.ssh/id",proxyJump:null,source:"config",warnings:[]}]);vi.spyOn(api,"saveConnection").mockImplementation(async(input)=>({...input,credential:undefined,hasCredential:false,createdAt:"",updatedAt:"",lastConnectedAt:null} as ConnectionProfile));});it("previews duplicates and imports only selected new hosts",async()=>{const changed=vi.fn().mockResolvedValue(undefined);const user=userEvent.setup();render(<OpenSshTools connections={[existing]} onChanged={changed} onError={vi.fn()}/>);await user.click(screen.getByRole("button",{name:"导入 config"}));expect(await screen.findByText("重复")).toBeInTheDocument();expect(screen.getByText("new-host")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"导入 1 项"}));await waitFor(()=>expect(api.saveConnection).toHaveBeenCalledTimes(1));expect(vi.mocked(api.saveConnection).mock.calls[0][0]).toMatchObject({host:"10.0.0.2",port:2222,username:"ubuntu",authType:"privateKey"});});it("shows generated public key and requires deployment preview",async()=>{dialog.save.mockResolvedValue("/Users/test/.ssh/id_ed25519");vi.spyOn(window,"prompt").mockReturnValue("test");vi.spyOn(window,"confirm").mockReturnValue(true);vi.spyOn(api,"generateSshKey").mockResolvedValue({privateKeyPath:"/Users/test/.ssh/id_ed25519",publicKeyPath:"/Users/test/.ssh/id_ed25519.pub",publicKey:"ssh-ed25519 AAA test",fingerprint:"SHA256:test"});const deploy=vi.spyOn(api,"deploySshKey").mockResolvedValue(undefined);const user=userEvent.setup();render(<OpenSshTools connections={[existing]} onChanged={vi.fn()} onError={vi.fn()}/>);await user.click(screen.getByRole("button",{name:"生成 Ed25519"}));expect(await screen.findByText("SHA-256 SHA256:test")).toBeInTheDocument();await user.selectOptions(screen.getByRole("combobox",{name:"部署到连接"}),"existing");await user.click(screen.getByRole("button",{name:"预览并部署"}));expect(deploy).toHaveBeenCalledWith("existing","ssh-ed25519 AAA test");});});
