import { Check,Clipboard,Download,FileKey2,KeyRound,Server,Upload } from "lucide-react";
import { open,save } from "@tauri-apps/plugin-dialog";
import { useMemo,useState } from "react";
import { api } from "../../lib/api";
import { errorMessage } from "../../lib/format";
import type { ConnectionProfile,GeneratedSshKey,OpenSshHost,SaveConnectionInput } from "../../types";

export function OpenSshTools({connections,onChanged,onError}:{connections:ConnectionProfile[];onChanged:()=>Promise<void>;onError:(message:string)=>void}){
  const[hosts,setHosts]=useState<OpenSshHost[]|null>(null);const[selected,setSelected]=useState<Set<number>>(new Set());const[generated,setGenerated]=useState<GeneratedSshKey|null>(null);const[deployTarget,setDeployTarget]=useState("");const duplicates=useMemo(()=>new Set((hosts??[]).map((host,index)=>connections.some((item)=>item.protocol==="ssh"&&item.host===host.hostname&&item.port===host.port&&item.username===(host.user??"root"))?index:-1).filter((index)=>index>=0)),[connections,hosts]);
  const chooseConfig=async()=>{const path=await open({multiple:false,directory:false,title:"选择 OpenSSH config"});if(!path)return;try{const items=await api.importOpenSshConfig(path);setHosts(items);setSelected(new Set(items.map((_,index)=>index).filter((index)=>!connections.some((connection)=>connection.protocol==="ssh"&&connection.host===items[index].hostname&&connection.port===items[index].port&&connection.username===(items[index].user??"root")))));}catch(error){onError(errorMessage(error));}};
  const importSelected=async()=>{if(!hosts)return;try{const imported=new Map<string,string>();for(const index of selected){const host=hosts[index];const id=crypto.randomUUID();const input:SaveConnectionInput={id,folderId:null,protocol:"ssh",name:host.alias,host:host.hostname,port:host.port,username:host.user??"root",authType:host.identityFile?"privateKey":"sshAgent",privateKeyPath:host.identityFile,hostKeyPolicy:"strict",note:`从 ${host.source} 导入`,tags:["OpenSSH"],encoding:"UTF-8",startupCommand:null,proxyId:null,environment:{},credential:""};await api.saveConnection(input);imported.set(host.alias,id);}for(const index of selected){const host=hosts[index];if(!host.proxyJump)continue;const jumpId=imported.get(host.proxyJump)??connections.find((item)=>item.protocol==="ssh"&&(item.name===host.proxyJump||item.host===host.proxyJump))?.id;if(!jumpId)continue;const proxy=await api.saveProxy({id:crypto.randomUUID(),name:`${host.alias} · ProxyJump`,type:"sshJump",host:"",port:22,username:null,jumpConnectionId:jumpId,credential:null});const connection=(await api.listConnections()).find((item)=>item.id===imported.get(host.alias));if(connection)await api.saveConnection({...connection,proxyId:proxy.id,credential:""});}await onChanged();setHosts(null);}catch(error){onError(errorMessage(error));}};
  const generate=async()=>{const path=await save({title:"保存 Ed25519 私钥",defaultPath:"id_ed25519"});if(!path)return;const comment=prompt("密钥注释",`cnshell@${new Date().toISOString().slice(0,10)}`);if(comment==null)return;try{setGenerated(await api.generateSshKey(path,comment));}catch(error){onError(errorMessage(error));}};
  const deploy=async()=>{if(!generated||!deployTarget)return;if(!confirm(`将以下公钥追加到目标 authorized_keys？\n\n${generated.fingerprint}\n${generated.publicKey}`))return;try{await api.deploySshKey(deployTarget,generated.publicKey);}catch(error){onError(errorMessage(error));}};
  return <section className="openssh-tools"><div className="section-heading"><div><h3><FileKey2 size={16}/>OpenSSH 配置与密钥</h3><p>私钥内容不会写入 CNshell 数据库或日志。</p></div><div><button className="mini-button" onClick={()=>void chooseConfig()}><Download size={13}/>导入 config</button><button className="mini-button" onClick={()=>void generate()}><KeyRound size={13}/>生成 Ed25519</button></div></div>{hosts&&<div className="openssh-import"><div className="openssh-host-list">{hosts.map((host,index)=><label key={`${host.source}-${host.alias}-${index}`} className={duplicates.has(index)?"duplicate":""}><input type="checkbox" checked={selected.has(index)} disabled={duplicates.has(index)} onChange={(event)=>setSelected((current)=>{const next=new Set(current);if(event.target.checked)next.add(index);else next.delete(index);return next;})}/><Server size={14}/><span><strong>{host.alias}</strong><small>{host.user??"root"}@{host.hostname}:{host.port}{host.identityFile?` · ${host.identityFile}`:""}</small>{host.proxyJump&&<small>ProxyJump {host.proxyJump}</small>}{host.warnings.map((warning)=><em key={warning}>{warning}</em>)}</span>{duplicates.has(index)&&<b>重复</b>}</label>)}</div><footer className="form-actions"><button className="button secondary" onClick={()=>setHosts(null)}>取消</button><button className="button primary" disabled={!selected.size} onClick={()=>void importSelected()}><Upload size={14}/>导入 {selected.size} 项</button></footer></div>}{generated&&<div className="generated-key"><Check size={18}/><div><strong>Ed25519 密钥已生成</strong><code>{generated.privateKeyPath}</code><span>SHA-256 {generated.fingerprint}</span><textarea readOnly value={generated.publicKey} aria-label="生成的公钥"/></div><button className="mini-button" onClick={()=>void navigator.clipboard.writeText(generated.publicKey)}><Clipboard size={12}/>复制公钥</button><label><span>部署到连接</span><select value={deployTarget} onChange={(event)=>setDeployTarget(event.target.value)}><option value="">选择 SSH 连接</option>{connections.filter((item)=>item.protocol==="ssh").map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button secondary" disabled={!deployTarget} onClick={()=>void deploy()}>预览并部署</button></div>}</section>;
}
