import { useEffect, useState } from "react";
import { Moon, Settings2 } from "lucide-react";
import { Modal } from "../../components/Modal";
import { useAppStore } from "../../store/app-store";
import type { AppSettings } from "../../types";
import { AdvancedSettings } from "./AdvancedSettings";
import { api } from "../../lib/api";
import { errorMessage } from "../../lib/format";
import { UpdateSettings } from "./UpdateSettings";
import { OpenSshTools } from "./OpenSshTools";
import { ProtocolSettings } from "./ProtocolSettings";
import { AutomationSettings } from "./AutomationSettings";
import { EncryptedSyncSettings } from "./EncryptedSyncSettings";

export default function SettingsModal(){const{settingsOpen,setSettingsOpen,settings,saveSettings,connections,refreshConnections,setError}=useAppStore();const[draft,setDraft]=useState(settings);useEffect(()=>{if(settingsOpen)setDraft(settings);},[settingsOpen,settings]);if(!settingsOpen)return null;const change=<K extends keyof AppSettings>(key:K,value:AppSettings[K])=>setDraft((current)=>({...current,[key]:value}));const clearHistory=async()=>{if(!confirm("清空这台 Mac 上的全部命令历史？此操作无法撤销。"))return;try{await api.clearHistory();}catch(error){setError(errorMessage(error));}};return <Modal title="设置" onClose={()=>setSettingsOpen(false)} wide><div className="settings-form"><section><h3><Moon size={16}/>外观</h3><label><span>主题</span><select value={draft.theme} onChange={(event)=>change("theme",event.target.value as AppSettings["theme"])}><option value="system">跟随系统</option><option value="dark">深色</option><option value="light">浅色</option><option value="highContrast">高对比度</option></select></label></section><section><h3><Settings2 size={16}/>会话</h3><label><span>监控刷新</span><select value={draft.monitorIntervalMs} onChange={(event)=>change("monitorIntervalMs",Number(event.target.value))}><option value={1000}>1 秒</option><option value={2000}>2 秒（推荐）</option><option value={5000}>5 秒</option></select></label><label className="check-row"><input type="checkbox" checked={draft.rememberCommandHistory} onChange={(event)=>change("rememberCommandHistory",event.target.checked)}/><span>保存非敏感命令历史</span></label><button className="button secondary" onClick={()=>void clearHistory()}>清空全部命令历史</button><label className="check-row"><input type="checkbox" checked={draft.confirmCloseActiveSession} onChange={(event)=>change("confirmCloseActiveSession",event.target.checked)}/><span>关闭活动会话前确认</span></label><label className="check-row"><input type="checkbox" checked={draft.showHiddenFiles} onChange={(event)=>change("showHiddenFiles",event.target.checked)}/><span>显示远端隐藏文件</span></label><label className="check-row"><input type="checkbox" checked={draft.showWelcomeHelp} onChange={(event)=>change("showWelcomeHelp",event.target.checked)}/><span>启动时显示使用帮助</span></label></section><OpenSshTools connections={connections} onChanged={refreshConnections} onError={(message)=>setError(message)}/><ProtocolSettings connections={connections} onError={(message)=>setError(message)}/><AutomationSettings connections={connections} onError={(message)=>setError(message)}/><EncryptedSyncSettings onError={(message)=>setError(message)}/><AdvancedSettings connections={connections} onChanged={refreshConnections} onError={(message)=>setError(message)}/><UpdateSettings onError={(message)=>setError(message)}/><footer className="form-actions"><button className="button secondary" onClick={()=>setSettingsOpen(false)}>取消</button><button className="button primary" onClick={()=>void saveSettings(draft).then(()=>setSettingsOpen(false))}>保存设置</button></footer></div></Modal>}
