#ifndef CNSHELL_MOSH_WINDOWS_CONFIG_H
#define CNSHELL_MOSH_WINDOWS_CONFIG_H

#define FD_ISSET_IS_CONST 1
#define HAVE_DECL_BE64TOH 0
#define HAVE_DECL_BETOH64 0
#define HAVE_DECL_BSWAP64 0
#define HAVE_DECL_FFS 0
#define HAVE_DECL___BUILTIN_BSWAP64 0
#define HAVE_DECL___BUILTIN_CTZ 0
#define HAVE_GETTIMEOFDAY 1
#define HAVE_LANGINFO_H 0
#define HAVE_MACH_ABSOLUTE_TIME 0
#define HAVE_CLOCK_GETTIME 0
#define HAVE_MEMORY 1
#define HAVE_STD_SHARED_PTR 1
#define HAVE_PTY_H 0
#define HAVE_UTIL_H 0

#define PACKAGE "mosh"
#define PACKAGE_NAME "mosh"
#define PACKAGE_STRING "mosh 1.4.0"
#define PACKAGE_TARNAME "mosh"
#define PACKAGE_VERSION "1.4.0"
#define VERSION "1.4.0"
#define USE_OPENSSL_AES 1

#endif
