import { useEffect,useRef,useState } from "react";
import { Braces,ChevronDown,ChevronUp,ExternalLink,LoaderCircle,Save,Search,Upload } from "lucide-react";
import { open } from "@tauri-apps/plugin-dialog";
import { diffLines,type Change } from "diff";
import { parse as parseYaml,stringify as stringifyYaml } from "yaml";
import { api } from "../../lib/api";
import { Modal } from "../../components/Modal";
import { errorMessage } from "../../lib/format";
import { usePlatformCapabilities } from "../../lib/platform";
import { IconButton } from "../../components/IconButton";
import { RemoteCodeEditor,type CodeEditorActions } from "./RemoteCodeEditor";
import { externalApplicationDialogOptions } from "./external-application";
import type { ExternalEditSession } from "../../types";
import "./TextEditor.css";

type Conflict={base:string;local:string;remote:string;remoteModifiedAt:number|null};

export function TextEditor({ sessionId, path, onClose }: { sessionId: string; path: string; onClose: () => void }) {
  const platform=usePlatformCapabilities();
  const [content,setContent]=useState("");const[base,setBase]=useState("");const[modifiedAt,setModifiedAt]=useState<number|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[saved,setSaved]=useState(false);const[conflict,setConflict]=useState<Conflict|null>(null);const[externalEdit,setExternalEdit]=useState<ExternalEditSession|null>(null);const editorRef=useRef<CodeEditorActions>(null);
  useEffect(()=>{api.openText(sessionId,path).then((file)=>{setContent(file.content);setBase(file.content);setModifiedAt(file.modifiedAt);}).catch((reason)=>setError(errorMessage(reason))).finally(()=>setLoading(false));},[path,sessionId]);
  const persist=async(expected=modifiedAt,value=content)=>{setSaving(true);setError(null);setSaved(false);try{await api.saveText(sessionId,path,value,expected);const current=await api.openText(sessionId,path);setContent(current.content);setBase(current.content);setModifiedAt(current.modifiedAt);setConflict(null);setSaved(true);return true;}catch(reason){const message=errorMessage(reason);if(message.includes("已被其他程序修改")){try{const remote=await api.openText(sessionId,path);setContent(value);setConflict({base,local:value,remote:remote.content,remoteModifiedAt:remote.modifiedAt});}catch(refreshError){setError(errorMessage(refreshError));}}else setError(message);return false;}finally{setSaving(false);}};
  const format=()=>{try{const lower=path.toLowerCase();if(lower.endsWith(".json")||lower.endsWith(".jsonc"))setContent(`${JSON.stringify(JSON.parse(content),null,2)}\n`);else if(/\.(ya?ml)$/.test(lower))setContent(stringifyYaml(parseYaml(content)));else{setError("当前文件类型不支持自动格式化");return;}setError(null);}catch(reason){setError(`格式化失败：${errorMessage(reason)}`);}};
  const overwrite=()=>{if(!conflict||!confirm("远端内容会被当前本地版本覆盖。确认继续？"))return;setContent(conflict.local);void persist(conflict.remoteModifiedAt);};
  const startExternal=async(application?:string)=>{try{setExternalEdit(await api.startExternalEdit(sessionId,path,application));}catch(reason){setError(errorMessage(reason));}};
  const chooseExternal=async()=>{const application=await open(externalApplicationDialogOptions(platform,`选择${platform.displayName}外部文本编辑器`));if(application)await startExternal(application);};
  const importExternal=async()=>{if(!externalEdit)return;setSaving(true);try{const snapshot=await api.readExternalEdit(externalEdit.id);const success=await persist(snapshot.expectedModifiedAt,snapshot.content);if(success){await api.discardExternalEdit(externalEdit.id);setExternalEdit(null);}}catch(reason){setError(errorMessage(reason));setSaving(false);}};
  const discardExternal=async()=>{if(!externalEdit)return;try{await api.discardExternalEdit(externalEdit.id);}catch{/* stale temporary files are cleaned on next launch */}setExternalEdit(null);};
  const close=()=>{if(externalEdit&&!confirm("外部编辑副本尚未回传，关闭将放弃该副本。继续？"))return;if(externalEdit)void api.discardExternalEdit(externalEdit.id);onClose();};
  return <Modal title={path.split("/").at(-1)??path} onClose={close} wide>{loading?<div className="loading-state"><LoaderCircle className="spin"/>读取远端文件…</div>:<div className="text-editor">{error&&<div className="inline-error">{error}</div>}{externalEdit&&<div className="external-edit-banner"><ExternalLink size={16}/><div><strong>外部编辑副本已打开</strong><code>{externalEdit.localPath}</code></div><button className="button secondary" onClick={()=>void discardExternal()}>放弃</button><button className="button primary" onClick={()=>void importExternal()} disabled={saving}><Upload size={14}/>读取并回传</button></div>}{conflict?<ConflictView conflict={conflict} onUseRemote={()=>{setContent(conflict.remote);setBase(conflict.remote);setModifiedAt(conflict.remoteModifiedAt);setConflict(null);}} onKeepEditing={()=>setConflict(null)} onOverwrite={overwrite}/>:<><div className="editor-toolbar"><IconButton icon={Search} label="搜索与替换" onClick={()=>editorRef.current?.search()}/><IconButton icon={ChevronUp} label="折叠全部" onClick={()=>editorRef.current?.fold()}/><IconButton icon={ChevronDown} label="展开全部" onClick={()=>editorRef.current?.unfold()}/><span className="toolbar-separator"/><button className="mini-button" onClick={format}><Braces size={13}/>格式化</button><button className="mini-button" onClick={()=>void startExternal()} disabled={Boolean(externalEdit)}><ExternalLink size={13}/>外部应用</button><button className="mini-button" onClick={()=>void chooseExternal()} disabled={Boolean(externalEdit)}>选择应用</button><span className="editor-path" title={path}>{path}</span></div><RemoteCodeEditor ref={editorRef} path={path} value={content} onChange={(value)=>{setContent(value);setSaved(false);}}/></>}<footer><span>{new Blob([content]).size.toLocaleString()} bytes · UTF-8{content!==base?" · 未保存":saved?" · 已保存":""}</span><div><button className="button secondary" onClick={close}>关闭</button><button className="button primary" onClick={()=>void persist()} disabled={saving||content===base}><Save size={15}/>{saving?"保存中…":"原子保存"}</button></div></footer></div>}</Modal>;
}

function ConflictView({conflict,onUseRemote,onKeepEditing,onOverwrite}:{conflict:Conflict;onUseRemote:()=>void;onKeepEditing:()=>void;onOverwrite:()=>void}){return <div className="conflict-view"><div className="conflict-warning"><strong>远端文件在编辑期间发生变化</strong><span>核对三个版本后选择如何继续，CNshell 不会静默覆盖。</span></div><div className="three-way-diff"><DiffColumn title="基础版本" changes={[{value:conflict.base} as Change]}/><DiffColumn title="本地版本" changes={diffLines(conflict.base,conflict.local)}/><DiffColumn title="远端版本" changes={diffLines(conflict.base,conflict.remote)}/></div><footer className="form-actions"><button className="button secondary" onClick={onKeepEditing}>继续编辑本地版本</button><button className="button secondary" onClick={onUseRemote}>使用远端版本</button><button className="button primary" onClick={onOverwrite}>以本地版本覆盖</button></footer></div>;}
function DiffColumn({title,changes}:{title:string;changes:Change[]}){return <section><h3>{title}</h3><pre>{changes.map((change,index)=><span className={change.added?"added":change.removed?"removed":""} key={index}>{change.value}</span>)}</pre></section>;}
